### ISSUE TITLE
Dissent Forwarder App

### ISSUE THREAD

**Issue by burrrata** [1Hive/dissent-voting-app#1]
The dissent forwarder allows Aragon organizations to allow actions to be taken only if the address has voted no or abstained from the most recent vote. The goal here would be to use with the redemptions app, so that you are only able to exit if you have not voted yes recently. It basically means that by voting yes on a proposal you are committing to the decision.
- Status: not under development

@lkngtn 
- The main reason this is relevant is that it ensures that people who dont vote for a proposal can exit (via redemptions), before those who voted for the the proposal are able to. I agree that deposits, dissent, delay are less important than redemptions/token-request, but they are important if we want to be able to frame the kit as "moloch" on aragon. 

@burrrata 
- I support this. Seems important to align incentives properly. 

@0xGabi 
- from reading the comments on [HackMD](https://hackmd.io/vehSeyRTRS-I20hYMmOtGg) it sounds like you generally support development on this app too?

**Comment by 0xGabi** [comment]
This might also be great opportunity to extend **aragonCLI** `dao acl create` command to include parameters
